require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
  - config/puma.rb
  - db/schema.rb
  - bin/**

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/VariableNumber:
  EnforcedStyle: snake_case

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
  - db/migrate/**/*.rb

Metrics/MethodLength:
  Exclude:
  - db/migrate/**/*.rb

# TODO: Remove this once CodeClimate stops being dumb
Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
