require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - config/puma.rb
  - db/schema.rb

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/VariableNumber:
  EnforcedStyle: snake_case

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
  - db/migrate/**/*.rb

Metrics/MethodLength:
  Exclude:
  - db/migrate/**/*.rb
