inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
  - requests/**/*_spec.rb

RSpec/ExampleLength:
  Exclude:
  - serializers/**/*_spec.rb

RSpec/MultipleExpectations:
  Exclude:
  - requests/**/*_spec.rb

Style/BlockDelimiters:
  Enabled: false
